# Generated by Django 2.1.1 on 2018-09-07 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=64, unique=True, verbose_name='Serial number of document')),
                ('date_of_issue', models.DateField(verbose_name='Date of issue')),
                ('type', models.CharField(choices=[('P', 'Passport'), ('SC', 'Student card'), ('DL', 'Drive license'), ('BC', 'Birth certificate')], max_length=1, verbose_name='')),
                ('scan_of_document', models.ImageField(blank=True, upload_to='products_images')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name, middle name and last name')),
                ('dob', models.DateField(verbose_name='Date of birth')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Sex of person')),
                ('cellphone_number', models.CharField(max_length=64, verbose_name='Cellphone number')),
                ('start_of_studying', models.DateField(verbose_name='Start of studying')),
                ('end_of_studying', models.DateField(verbose_name='End of studying')),
                ('group', models.CharField(max_length=64, verbose_name='Studying group')),
                ('university_name', models.CharField(max_length=64, verbose_name='Name of university')),
            ],
        ),
        migrations.AddField(
            model_name='documents',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Person'),
        ),
    ]
